Convert str to byte object in linuxhelper's kern_set_EFI_variable (#2536)
* Convert str to byte object in linuxhelper's kern_set_EFI_variable

This is required to be able to successfuly run the common.uefi.access_uefispec -a modify
test from under Linux and resolve the following error:

ERROR: Exception occurred during chipsec.modules.common.uefi.access_uefispec.run(): 'argument for 's' must be a bytes object'

Signed-off-by: Tamas K Lengyel <tamas.lengyel@oracle.com>

* Use recommended best practice isinstance for type checking

Co-authored-by: Nathaniel Mitchell <nathaniel.p.mitchell@intel.com>

---------

Signed-off-by: Tamas K Lengyel <tamas.lengyel@oracle.com>
Co-authored-by: Nathaniel Mitchell <nathaniel.p.mitchell@intel.com>