Remove hex_to_text from logger
This function was never used. Moreover it does not work with numbers
with an odd number of hexdigits because `binascii.unhexlify(f'{value:x}')`
fails with:

    >>> hex_to_text(1)
    binascii.Error: Odd-length string

Signed-off-by: Nicolas Iooss <nicolas.iooss_git@polytechnique.org>