Format bytes with .hex() instead of :8X
Using `{buf:8X}` does not work in `LinuxNativeHelper.write_msr`: this
raises an expection

    TypeError: unsupported format string passed to bytes.__format__

Use `{buf.hex()}` instead to format the bytes in the error message.

Signed-off-by: Nicolas Iooss <nicolas.iooss_git@polytechnique.org>