linuxhelper: assign default value if None is being passed in
linuxhelper's kern_set_EFI_variable only sets default value for attr if no
value has been passed in. In some call-chains (uefi var-write) however None
is being passed in, resulting in the following error from:

struct.error: required argument is not an integer

Make attr optional input and override if value is None with default value.

Signed-off-by: Tamas K Lengyel <tamas.lengyel@oracle.com>